"""
config.py — Centralized settings for the FastAPI ML service.

All environment variables and AI tuning parameters live here.
Using pydantic-settings for automatic .env loading + type validation.

Environment file: civicai/ml-service/.env
"""

from pydantic_settings import BaseSettings
from pathlib import Path

# Resolve the root directory of the ml-service (parent of app/)
BASE_DIR = Path(__file__).resolve().parent.parent


class Settings(BaseSettings):

    # ─── Roboflow (Image Classification via Hosted Workflow) ────────────────────
    # Get your API key at: https://roboflow.com
    # Workspace and Workflow IDs are visible in your Roboflow dashboard.
    ROBOFLOW_API_KEY: str = ""
    ROBOFLOW_WORKSPACE: str = ""   # e.g. "priyanshus-workspace-5wkav"
    ROBOFLOW_WORKFLOW_ID: str = ""  # e.g. "detect-and-classify"

    # ─── Gemini (Summarization) ────────────────────────────────────────────────
    # Get your API key at: https://aistudio.google.com/
    GEMINI_API_KEY: str = ""

    # ─── Duplicate Detection ───────────────────────────────────────────────────
    # Cosine similarity threshold: above this score → complaints are duplicates.
    # Range: 0.0 (completely different) → 1.0 (identical meaning)
    # 0.82 catches rewording ("big pothole" ≈ "huge road hole")
    # without over-merging genuinely different complaints.
    SIMILARITY_THRESHOLD: float = 0.82

    # Geographic radius for pre-filtering nearby complaints before semantic search.
    # ~50m is roughly half a city block.
    GEO_RADIUS_METERS: float = 50.0

    # ─── Multimodal Fusion Weights ─────────────────────────────────────────────
    # Adaptive weighting strategy:
    #   - When image confidence is HIGH (≥ IMAGE_CONFIDENCE_THRESHOLD):
    #     Image gets more weight (more reliable prediction)
    #   - When image confidence is LOW:
    #     Text gets more weight (image is blurry/unclear)
    #
    # This makes the fusion layer adaptive rather than using a fixed split.

    # Threshold: above this, the image is considered confident
    IMAGE_CONFIDENCE_THRESHOLD: float = 0.70

    # Weights for HIGH image confidence scenario
    HIGH_IMAGE_WEIGHT: float = 0.60
    HIGH_TEXT_WEIGHT: float = 0.40

    # Weights for LOW image confidence scenario (text dominates)
    LOW_IMAGE_WEIGHT: float = 0.20
    LOW_TEXT_WEIGHT: float = 0.80

    # ─── ChromaDB ─────────────────────────────────────────────────────────────
    CHROMA_COLLECTION: str = "complaints"
    # Persistent storage path — data survives server restarts
    CHROMA_PERSIST_DIR: str = str(BASE_DIR / "chroma_db")

    # ─── Model Paths ──────────────────────────────────────────────────────────
    # Text classifier: generated by running app/training/train_text_classifier.py
    TEXT_CLASSIFIER_PATH: str = str(BASE_DIR / "app" / "models" / "text_classifier.pkl")

    # ─── Embedding Model ──────────────────────────────────────────────────────
    # all-MiniLM-L6-v2: 384-dim, ~80MB, excellent for semantic similarity.
    # Downloads automatically on first run → ~/.cache/huggingface/
    EMBEDDING_MODEL_NAME: str = "all-MiniLM-L6-v2"

    # ─── Category Labels ──────────────────────────────────────────────────────
    # Must match the labels used by Roboflow and in the text classifier training data.
    CATEGORIES: list = [
        "pothole",
        "garbage",
        "waterlogging",
        "broken_streetlight",
        "road_damage",
        "others",
    ]

    class Config:
        env_file = str(BASE_DIR / ".env")
        env_file_encoding = "utf-8"
        extra = "ignore"


# Singleton instance — import this everywhere in the app
settings = Settings()
