-- Phase 4 AI Integration: Supabase Schema Migration
-- Run this in your Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- Safe to run multiple times (uses IF NOT EXISTS / ADD COLUMN IF NOT EXISTS)

-- ─── Add AI-enriched columns to complaints table ─────────────────────────────

ALTER TABLE complaints
  ADD COLUMN IF NOT EXISTS ai_category TEXT,
  ADD COLUMN IF NOT EXISTS ai_confidence FLOAT,
  ADD COLUMN IF NOT EXISTS ai_summary TEXT,
  ADD COLUMN IF NOT EXISTS ai_routing TEXT,
  ADD COLUMN IF NOT EXISTS report_count INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS is_duplicate BOOLEAN DEFAULT FALSE;

-- ─── Comments for documentation ───────────────────────────────────────────────
COMMENT ON COLUMN complaints.ai_category IS
  'Category predicted by the AI pipeline (CNN + TF-IDF fusion)';

COMMENT ON COLUMN complaints.ai_confidence IS
  'Confidence score (0.0-1.0) of the AI category prediction';

COMMENT ON COLUMN complaints.ai_summary IS
  'Concise 1-2 sentence summary generated by Gemini API';

COMMENT ON COLUMN complaints.ai_routing IS
  'Municipal department routing suggestion from Gemini API';

COMMENT ON COLUMN complaints.report_count IS
  'Number of times this complaint has been reported (1 = first report, >1 = merged duplicates)';

COMMENT ON COLUMN complaints.is_duplicate IS
  'True if this complaint was identified as a semantic duplicate and merged into another';

-- ─── Optional: Create index for geo queries ───────────────────────────────────
-- Speeds up the bounding-box geo-filter query in complaintModel.getComplaintsByLocation()
CREATE INDEX IF NOT EXISTS idx_complaints_location
  ON complaints (latitude, longitude)
  WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

-- ─── Verify the migration ─────────────────────────────────────────────────────
SELECT
  column_name,
  data_type,
  column_default
FROM information_schema.columns
WHERE table_name = 'complaints'
  AND column_name IN (
    'ai_category', 'ai_confidence', 'ai_summary',
    'ai_routing', 'report_count', 'is_duplicate'
  )
ORDER BY column_name;
